import { findDefinitionInContent } from './src/editor/go-to-definition.js';
const content = "function a() {}\nfunction foo() {\n  console.log(1);\n}\n";
const safeWord = 'foo';
const regex = new RegExp('(?:function|func|fn|def|class|struct|interface|type|trait|enum|impl)\\s+' + safeWord + '\\b');
const match = regex.exec(content);
console.log('Match index:', match.index);
console.log('Match text:', match[0]);
const beforeMatch = content.substring(0, match.index);
console.log('beforeMatch:', JSON.stringify(beforeMatch));
const lines = beforeMatch.split('\n');
console.log('lines:', lines);
console.log('result:', findDefinitionInContent('foo', content));
